require: rubocop-rails

Style/Encoding:
  Enabled: true

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 30

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

AllCops:
    NewCops: enable