name: Rubocop
on: [pull_request]
jobs:
  rubocop:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true
      - name: Run rubocop
        run: bundle exec rubocop
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.5
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_database
        options: --healt-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Create Data base
        env:
          RAILS_ENV: "test"
          DB_USER: postgres
          DB_PASSWORD: postgres
          DATABASE_URL: "postgres://postgres@localhost:5432/test_database"
      - name: Run tests
        run: |
          bundle exec rake db:create
          bundle exec rake db:schema:load
          bundle exec rake